// Code generated by "stringer -type=Button -trimprefix Button"; DO NOT EDIT.

package mikro

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ButtonProject-0]
	_ = x[ButtonFavorites-1]
	_ = x[ButtonBrowser-2]
	_ = x[ButtonVolume-3]
	_ = x[ButtonSwing-4]
	_ = x[ButtonTempo-5]
	_ = x[ButtonPlugin-6]
	_ = x[ButtonSampling-7]
	_ = x[ButtonArrowLeft-8]
	_ = x[ButtonArrowRight-9]
	_ = x[ButtonPitch-10]
	_ = x[ButtonMod-11]
	_ = x[ButtonPerform-12]
	_ = x[ButtonNotes-13]
	_ = x[ButtonGroup-14]
	_ = x[ButtonAuto-15]
	_ = x[ButtonLock-16]
	_ = x[ButtonNoteRepeat-17]
	_ = x[ButtonRestart-18]
	_ = x[ButtonErase-19]
	_ = x[ButtonTap-20]
	_ = x[ButtonFollow-21]
	_ = x[ButtonPlay-22]
	_ = x[ButtonRec-23]
	_ = x[ButtonStop-24]
	_ = x[ButtonShift-25]
	_ = x[ButtonFixedVel-26]
	_ = x[ButtonPadMode-27]
	_ = x[ButtonKeyboard-28]
	_ = x[ButtonChords-29]
	_ = x[ButtonStep-30]
	_ = x[ButtonScene-31]
	_ = x[ButtonPattern-32]
	_ = x[ButtonEvents-33]
	_ = x[ButtonVariation-34]
	_ = x[ButtonDuplicate-35]
	_ = x[ButtonSelect-36]
	_ = x[ButtonSolo-37]
	_ = x[ButtonMute-38]
	_ = x[ButtonEncoder-39]
}

const _Button_name = "ProjectFavoritesBrowserVolumeSwingTempoPluginSamplingArrowLeftArrowRightPitchModPerformNotesGroupAutoLockNoteRepeatRestartEraseTapFollowPlayRecStopShiftFixedVelPadModeKeyboardChordsStepScenePatternEventsVariationDuplicateSelectSoloMuteEncoder"

var _Button_index = [...]uint8{0, 7, 16, 23, 29, 34, 39, 45, 53, 62, 72, 77, 80, 87, 92, 97, 101, 105, 115, 122, 127, 130, 136, 140, 143, 147, 152, 160, 167, 175, 181, 185, 190, 197, 203, 212, 221, 227, 231, 235, 242}

func (i Button) String() string {
	if i < 0 || i >= Button(len(_Button_index)-1) {
		return "Button(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Button_name[_Button_index[i]:_Button_index[i+1]]
}
