// Code generated by "stringer -type=Color -trimprefix=Color"; DO NOT EDIT.

package mikro

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorOff-0]
	_ = x[ColorRed-1]
	_ = x[ColorOrange-2]
	_ = x[ColorLightOrange-3]
	_ = x[ColorWarmYellow-4]
	_ = x[ColorYellow-5]
	_ = x[ColorLime-6]
	_ = x[ColorGreen-7]
	_ = x[ColorMint-8]
	_ = x[ColorCyan-9]
	_ = x[ColorTurquoise-10]
	_ = x[ColorBlue-11]
	_ = x[ColorPlum-12]
	_ = x[ColorViolet-13]
	_ = x[ColorPurple-14]
	_ = x[ColorMagenta-15]
	_ = x[ColorFuchsia-16]
	_ = x[ColorWhite-17]
}

const _Color_name = "OffRedOrangeLightOrangeWarmYellowYellowLimeGreenMintCyanTurquoiseBluePlumVioletPurpleMagentaFuchsiaWhite"

var _Color_index = [...]uint8{0, 3, 6, 12, 23, 33, 39, 43, 48, 52, 56, 65, 69, 73, 79, 85, 92, 99, 104}

func (i Color) String() string {
	if i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
