// Code generated by "stringer -type=ColorLevel -trimprefix=ColorLevel"; DO NOT EDIT.

package mikro

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorLevelLow-0]
	_ = x[ColorLevelMedium-1]
	_ = x[ColorLevelHigh-2]
	_ = x[ColorLevelFaded-3]
}

const _ColorLevel_name = "LowMediumHighFaded"

var _ColorLevel_index = [...]uint8{0, 3, 9, 13, 18}

func (i ColorLevel) String() string {
	if i >= ColorLevel(len(_ColorLevel_index)-1) {
		return "ColorLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColorLevel_name[_ColorLevel_index[i]:_ColorLevel_index[i+1]]
}
