// Code generated by "stringer -type=Intensity -trimprefix=Intensity"; DO NOT EDIT.

package mikro

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IntensityLow-0]
	_ = x[IntensityOff-1]
	_ = x[IntensityMedium-2]
	_ = x[IntensityHigh-3]
}

const _Intensity_name = "LowOffMediumHigh"

var _Intensity_index = [...]uint8{0, 3, 6, 12, 16}

func (i Intensity) String() string {
	if i >= Intensity(len(_Intensity_index)-1) {
		return "Intensity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Intensity_name[_Intensity_index[i]:_Intensity_index[i+1]]
}
